version: '3.8'

services:
  fastcgi-app:
    build: .
    container_name: fastcgi-server
    restart: always

  web:
    image: httpd:2.4
    container_name: apache-web
    ports:
      - "8080:80"
    volumes:
      - ./src/main/resources:/usr/local/apache2/htdocs/
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - fastcgi-app